"""uuid_primary_keys_baseline

Revision ID: 166d4c2dd442
Revises: 
Create Date: 2026-03-15 17:53:42.563899+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '166d4c2dd442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_path', sa.String(length=500), nullable=True),
    sa.Column('remote_url', sa.String(length=500), nullable=True),
    sa.Column('remote_branch', sa.String(length=100), server_default='main', nullable=False),
    sa.Column('remote_credential_ref', sa.String(length=500), nullable=True),
    sa.Column('output_comment_style', sa.String(length=10), server_default='#', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_projects_org_name')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('quickpads',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owner_username', sa.String(length=200), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_quickpads_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quickpads'))
    )
    op.create_index(op.f('ix_quickpads_organization_id'), 'quickpads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_quickpads_owner_username'), 'quickpads', ['owner_username'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('secret_type', postgresql.ENUM('env', 'vault', 'db', name='secrettype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('vault_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("secret_type != 'vault' OR vault_path IS NOT NULL", name=op.f('ck_secrets_vault_requires_path')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_secrets_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_secrets_org_name')
    )
    op.create_index(op.f('ix_secrets_name'), 'secrets', ['name'], unique=False)
    op.create_index(op.f('ix_secrets_organization_id'), 'secrets', ['organization_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_api_key', sa.String(length=512), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_base_url', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_system_settings_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_org_id'), 'system_settings', ['org_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_ldap', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_api_keys_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_keys_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_table('custom_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_custom_filters_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_filters')),
    sa.UniqueConstraint('name', 'scope', 'project_id', name='uq_custom_filter_name')
    )
    op.create_table('custom_macros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_custom_macros_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_macros')),
    sa.UniqueConstraint('name', 'scope', 'project_id', name='uq_custom_macro_name')
    )
    op.create_table('custom_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_custom_objects_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_objects')),
    sa.UniqueConstraint('name', 'project_id', name='uq_custom_object_name')
    )
    op.create_table('features',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snippet_path', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_features_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features')),
    sa.UniqueConstraint('project_id', 'name', name='uq_features_project_name')
    )
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_path', sa.String(length=500), nullable=True),
    sa.Column('parent_template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_snippet', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_hidden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('history_label_param', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_templates_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_template_id'], ['templates.id'], name=op.f('fk_templates_parent_template_id_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_templates_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('project_id', 'name', name='uq_templates_project_name')
    )
    op.create_index(op.f('ix_templates_created_by'), 'templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    op.create_index(op.f('ix_templates_parent_template_id'), 'templates', ['parent_template_id'], unique=False)
    op.create_index(op.f('ix_templates_project_id'), 'templates', ['project_id'], unique=False)
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scope', postgresql.ENUM('global', 'project', 'template', 'feature', name='parameterscope'), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('feature_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('widget_type', postgresql.ENUM('text', 'number', 'select', 'multiselect', 'textarea', 'readonly', 'hidden', name='widgettype'), server_default='text', nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('validation_regex', sa.String(length=500), nullable=True),
    sa.Column('is_derived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('derived_expression', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('visible_when', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'global'   AND organization_id IS NOT NULL AND project_id IS NULL    AND template_id IS NULL  AND feature_id IS NULL) OR (scope = 'project'  AND project_id IS NOT NULL       AND organization_id IS NULL AND template_id IS NULL AND feature_id IS NULL) OR (scope = 'template' AND template_id IS NOT NULL       AND organization_id IS NULL AND project_id IS NULL  AND feature_id IS NULL) OR (scope = 'feature'  AND feature_id IS NOT NULL        AND organization_id IS NULL AND project_id IS NULL  AND template_id IS NULL)", name=op.f('ck_parameters_scope_fk_mutual_exclusivity')),
    sa.CheckConstraint('NOT is_derived OR derived_expression IS NOT NULL', name=op.f('ck_parameters_derived_requires_expression')),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_parameters_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_parameters_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_parameters_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_parameters_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameters'))
    )
    op.create_index(op.f('ix_parameters_feature_id'), 'parameters', ['feature_id'], unique=False)
    op.create_index(op.f('ix_parameters_name'), 'parameters', ['name'], unique=False)
    op.create_index(op.f('ix_parameters_organization_id'), 'parameters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_parameters_project_id'), 'parameters', ['project_id'], unique=False)
    op.create_index(op.f('ix_parameters_scope'), 'parameters', ['scope'], unique=False)
    op.create_index(op.f('ix_parameters_template_id'), 'parameters', ['template_id'], unique=False)
    op.create_index('uix_parameters_name_feature', 'parameters', ['name', 'feature_id'], unique=True, postgresql_where=sa.text("scope = 'feature'"))
    op.create_index('uix_parameters_name_org_global', 'parameters', ['name', 'organization_id'], unique=True, postgresql_where=sa.text("scope = 'global'"))
    op.create_index('uix_parameters_name_project', 'parameters', ['name', 'project_id'], unique=True, postgresql_where=sa.text("scope = 'project'"))
    op.create_index('uix_parameters_name_template', 'parameters', ['name', 'template_id'], unique=True, postgresql_where=sa.text("scope = 'template'"))
    op.create_table('render_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('template_git_sha', sa.String(length=64), nullable=False),
    sa.Column('resolved_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=False),
    sa.Column('rendered_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('rendered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_label', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['rendered_by'], ['users.id'], name=op.f('fk_render_history_rendered_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_render_history_template_id_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_history'))
    )
    op.create_index(op.f('ix_render_history_rendered_at'), 'render_history', ['rendered_at'], unique=False)
    op.create_index(op.f('ix_render_history_rendered_by'), 'render_history', ['rendered_by'], unique=False)
    op.create_index(op.f('ix_render_history_template_id'), 'render_history', ['template_id'], unique=False)
    op.create_table('render_presets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_render_presets_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_render_presets_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_presets'))
    )
    op.create_index(op.f('ix_render_presets_template_id'), 'render_presets', ['template_id'], unique=False)
    op.create_table('render_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('http_method', sa.String(length=10), server_default='POST', nullable=False),
    sa.Column('auth_header', sa.Text(), nullable=True),
    sa.Column('payload_template', sa.Text(), nullable=True),
    sa.Column('trigger_on', sa.String(length=20), server_default='persist', nullable=False),
    sa.Column('on_error', sa.String(length=20), server_default='warn', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='10', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(project_id IS NOT NULL AND template_id IS NULL) OR (project_id IS NULL AND template_id IS NOT NULL)', name=op.f('ck_render_webhooks_ck_webhook_scope')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_render_webhooks_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_render_webhooks_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_render_webhooks_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_webhooks'))
    )
    op.create_index(op.f('ix_render_webhooks_organization_id'), 'render_webhooks', ['organization_id'], unique=False)
    op.create_table('template_features',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feature_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_template_features_feature_id_features'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_template_features_template_id_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_features')),
    sa.UniqueConstraint('template_id', 'feature_id', name='uq_template_feature')
    )
    op.create_index(op.f('ix_template_features_feature_id'), 'template_features', ['feature_id'], unique=False)
    op.create_index(op.f('ix_template_features_template_id'), 'template_features', ['template_id'], unique=False)
    op.create_table('parameter_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('condition_param', sa.String(length=200), nullable=True),
    sa.Column('condition_value', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], name=op.f('fk_parameter_options_parameter_id_parameters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parameter_options'))
    )
    op.create_index(op.f('ix_parameter_options_parameter_id'), 'parameter_options', ['parameter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameter_options_parameter_id'), table_name='parameter_options')
    op.drop_table('parameter_options')
    op.drop_index(op.f('ix_template_features_template_id'), table_name='template_features')
    op.drop_index(op.f('ix_template_features_feature_id'), table_name='template_features')
    op.drop_table('template_features')
    op.drop_index(op.f('ix_render_webhooks_organization_id'), table_name='render_webhooks')
    op.drop_table('render_webhooks')
    op.drop_index(op.f('ix_render_presets_template_id'), table_name='render_presets')
    op.drop_table('render_presets')
    op.drop_index(op.f('ix_render_history_template_id'), table_name='render_history')
    op.drop_index(op.f('ix_render_history_rendered_by'), table_name='render_history')
    op.drop_index(op.f('ix_render_history_rendered_at'), table_name='render_history')
    op.drop_table('render_history')
    op.drop_index('uix_parameters_name_template', table_name='parameters', postgresql_where=sa.text("scope = 'template'"))
    op.drop_index('uix_parameters_name_project', table_name='parameters', postgresql_where=sa.text("scope = 'project'"))
    op.drop_index('uix_parameters_name_org_global', table_name='parameters', postgresql_where=sa.text("scope = 'global'"))
    op.drop_index('uix_parameters_name_feature', table_name='parameters', postgresql_where=sa.text("scope = 'feature'"))
    op.drop_index(op.f('ix_parameters_template_id'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_scope'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_project_id'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_organization_id'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_name'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_feature_id'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_templates_project_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_parent_template_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_created_by'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_table('features')
    op.drop_table('custom_objects')
    op.drop_table('custom_macros')
    op.drop_table('custom_filters')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_org_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_secrets_organization_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_name'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index(op.f('ix_quickpads_owner_username'), table_name='quickpads')
    op.drop_index(op.f('ix_quickpads_organization_id'), table_name='quickpads')
    op.drop_table('quickpads')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
