"""add_custom_filters_objects

Revision ID: c6743f47e62d
Revises: a07a1c458d14
Create Date: 2026-02-23 16:34:12.186985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6743f47e62d'
down_revision: Union[str, None] = 'a07a1c458d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_custom_filters_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_filters')),
    sa.UniqueConstraint('name', 'scope', 'project_id', name='uq_custom_filter_name')
    )
    op.create_table('custom_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_custom_objects_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_objects')),
    sa.UniqueConstraint('name', 'project_id', name='uq_custom_object_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_objects')
    op.drop_table('custom_filters')
    # ### end Alembic commands ###
