"""add_parameter_is_active

Revision ID: ebbd44c23458
Revises: b59743004dae
Create Date: 2026-02-21 18:29:45.438944+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebbd44c23458'
down_revision: Union[str, None] = 'b59743004dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'is_active')
    # ### end Alembic commands ###
