"""add_user_auth_fields

Revision ID: 7e8d9aa2e820
Revises: ebbd44c23458
Create Date: 2026-02-22 21:07:56.017512+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8d9aa2e820'
down_revision: Union[str, None] = 'ebbd44c23458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_ldap', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'is_ldap')
    # ### end Alembic commands ###
